apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: final-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chervinskyds/danit-final-project_cds.git
    targetRevision: main
    path: manifests   # у тебе маніфести тут
  destination:
    server: https://kubernetes.default.svc
    namespace: final-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true