name: Build & Push Docker image

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/docker-build-push.yml"
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/danit-cds-final-proj-app:${{ steps.vars.outputs.TAG }} ./app

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/danit-cds-final-proj-app:${{ steps.vars.outputs.TAG }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/danit-cds-final-proj-app:${{ steps.vars.outputs.TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/danit-cds-final-proj-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/danit-cds-final-proj-app:latest
