name: Build & Push Docker image

on:
  push:
    paths:
      - "app/**"
      - ".github/workflowstest/docker-build-push-test.yml"
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/danit-app:${{ steps.vars.outputs.TAG }} app

      - name: Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/danit-app:${{ steps.vars.outputs.TAG }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/danit-app:${{ steps.vars.outputs.TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/danit-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/danit-app:latest
